authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pyproject.toml
- tox.ini
- .yamllint
- .ansible-lint
- .pre-commit-config.yaml
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- requirements.txt
- requirements-molecule.txt
- '**/requirements-molecule.txt'
- '**/requirements.txt'
dependencies: {}
description: Roles and modules related to setting up borgbackup and borgmatic software
documentation: https://github.com/maxhoesel-ansibleansible-collection-borg
homepage: https://github.com/maxhoesel-ansibleansible-collection-borg
issues: https://github.com/maxhoesel-ansibleansible-collection-borg/issues
license_file: LICENSE
name: borgbackup
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansibleansible-collection-borg
tags:
- borg
- backup
- system
version: 0.1.15
