authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- .config
- .vscode
- dist
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- .yamllint
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- .pre-commit-config.yaml
- .readthedocs.yaml
- pyproject.toml
- requirements.txt
- tox.ini
- '**/requirements.txt'
dependencies:
  community.general: '>=1.0.0'
description: Setup linux backup using borg and the borgmatic wrapper
issues: https://github.com/maxhoesel-ansible/ansible-collection-borgbackup/issues
license_file: LICENSE
name: borgbackup
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansible/ansible-collection-borgbackup
tags:
- borg
- application
- backup
- linux
version: '0.1.15'
