---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/collections/requirements.yml
    role-file: molecule/default/collections/requirements.yml
driver:
  name: docker
  network:
    - name: borgmatic
      driver: bridge
platforms:
  # Note on containers:
  # - We use the images provided by geerlingguy, as they provide out-of-the-box
  #   support for Ansible and systemd (needed to test service management).
  # - The containers run as privileged containers so that we can
  #   use systemd functionality. This *should* be possible with unpriliged
  #   containers as well, but is quite the headache.
  # - they are connected to a shared network to allow simulating a remote CA
  - name: borgmatic-server
    hostname: borgmatic-server.localdomain
    groups:
      - ubuntu
      - servers
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: borgmatic

  - name: borgmatic-ubuntu-20
    hostname: borgmatic-ubuntu-20.localdomain
    groups:
      - ubuntu
      - clients
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: borgmatic

provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: yes

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check # also run check mode in regular tests
    - side_effect
    - verify
    - destroy

verifier:
  name: ansible
