---
platforms:
  - name: borgmatic-ubuntu-22
    groups:
      - ubuntu
      - clients
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    networks:
      - name: molecule-borgmatic

  - name: borgmatic-ubuntu-20
    groups:
      - ubuntu
      - clients
    image: "docker.io/geerlingguy/docker-ubuntu2004-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    networks:
      - name: molecule-borgmatic

  - name: borgmatic-debian-12
    groups:
      - debian
      - clients
    image: "docker.io/geerlingguy/docker-debian12-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    networks:
      - name: molecule-borgmatic

  - name: borgmatic-debian-11
    groups:
      - debian
      - clients
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    networks:
      - name: molecule-borgmatic

  # We use the borg server_role to install a backup server.
  # Ideally we'd use some externally-prepared docker container like
  # https://github.com/grantbevis/borg-server instead, to prevent depending on our own collection.
  - name: borgmatic-server
    groups:
      - ubuntu
      - servers
    image: "docker.io/geerlingguy/docker-ubuntu2004-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    networks:
      - name: molecule-borgmatic

provisioner:
  playbooks:
    verify: ../verify.yml
