version: 2.1

orbs:
  collection-testing: maxhoesel-ansible/ansible-collection-testing@0.3.5

jobs:
  build-install:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - collection-testing/install-requirements-txt:
          file: requirements.txt
      - collection-testing/build-install-collection
  modules-sanity:
    executor: collection-testing/default
    steps:
      - checkout
      - collection-testing/install-podman-on-ubuntu
      - collection-testing/install-requirements-txt
      - run:
          command: tests/test-modules-sanity
  modules-integration:
    executor: collection-testing/default
    steps:
      - checkout
      - collection-testing/install-podman-on-ubuntu
      - collection-testing/install-requirements-txt
      - run:
          command: tests/test-modules-integration

filters: &tagged
  tags:
    # Official Semver Regex. Yes, it's LOOOONG
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  branches:
    ignore: /.*/

workflows:
  ci:
    jobs:
      - build-install
      - collection-testing/pre-commit-lint
      #- collection-testing/antsibull-docs
      - collection-testing/tox-role-scenarios:
          parallelism: 8
          resource-class: large
      - collection-testing/publish-github:
          context: collection-publishing
          filters: *tagged
      - collection-testing/publish-galaxy:
          context: collection-publishing
          filters: *tagged
      #- modules-sanity
      #- modules-integration
