version: 2.1

orbs:
  collection-testing: maxhoesel-ansible/ansible-collection-testing@0.6.0

filters: &semver-tagged
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*$/
  branches:
    ignore: /.*/

workflows:
  ci:
    jobs:
      - collection-testing/pytest:
          name: Test (ansible-<< matrix.ansible_python_version_tuple >>)
          pytest_args: >
            --ci
            --ansible-version "$ANSIBLE_VERSION"
            --node-python-version "$PYTHON_VERSION"
          parallelism: 3
          matrix:
            parameters:
              ansible_python_version_tuple: ["2.20,3.9", "2.21,3.9"]
          pre-steps:
            - run:
              name: Split version tuples
              command: |
                export ANSIBLE_VERSION_STRING=$(echo "<< matrix.ansible_python_version_tuple >>" | cut -d ',' -f 1)
                export PYTHON_VERSION_STRING=$(echo "<< matrix.ansible_python_version_tuple >>" | cut -d ',' -f 2)
                echo export ANSIBLE_VERSION="$ANSIBLE_VERSION_STRING" >> "$BASH_ENV"
                echo export PYTHON_VERSION="$PYTHON_VERSION_STRING" >> "$BASH_ENV"
      - collection-testing/pre-commit-lint:
          name: Lint
      - collection-testing/publish-github:
          name: Publish Release to GitHub
          context: collection-publishing
          filters: *semver-tagged
      - collection-testing/publish-galaxy:
          name: Publish to Galaxy
          context: collection-publishing
          filters: *semver-tagged
