version: 2.1

orbs:
  collection-testing: maxhoesel-ansible/ansible-collection-testing@0.6.2

filters: &semver-tagged
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*$/
  branches:
    ignore: /.*/

workflows:
  ci:
    jobs:
      - collection-testing/pytest:
          name: Pytest (<< matrix.pytest_args >>)
          parallelism: 3
          matrix:
            parameters:
              pytest_args:
                - --ci --ansible-version 2.20 --node-python-version 3.9
                - --ci --ansible-version 2.21 --node-python-version 3.9
      - collection-testing/pre-commit-lint:
          name: Lint
      - collection-testing/publish-github:
          name: Publish Release to GitHub
          context: collection-publishing
          filters: *semver-tagged
      - collection-testing/publish-galaxy:
          name: Publish to Galaxy
          context: collection-publishing
          filters: *semver-tagged
