---
- name: Converge
  hosts: all
  tasks:
    - name: "Include borgmatic"
      include_role:
        name: "borgmatic"
      vars:
        borgmatic_run_backup: yes
        borgmatic_run_backup_no_block: false
        borgmatic_config:
          location:
            source_directories:
              - /etc
            repositories:
              - /tmp/myrepo
          storage:
            encryption_passphrase: molecule-test
          retention:
            keep_daily: 3
        borgmatic_schedule_check_job: yes
        # Don't actually trigger the timer, we run the check job manually
        borgmatic_schedule_check_job_time: "2099-12-31"

    - name: Wait for backup to finish
      wait_for:
        path: "/tmp/myrepo/lock.roster"
        state: absent
        timeout: 120
