---
- name: Converge
  hosts: clients
  tasks:
    - name: "Include borgmatic"
      include_role:
        name: "borgmatic"
      vars:
        borgmatic_run_backup: yes
        borgmatic_run_backup_no_block: false
        borgmatic_config:
          location:
            source_directories:
              - /etc
            repositories:
              - ssh://borg@borgmatic-server/./molecule
          storage:
            encryption_passphrase: molecule-test
          retention:
            keep_daily: 3
        # setup is done manually in "prepare"
        borgmatic_ssh_manage_key: false
        borgmatic_ssh_key_path: /root/.ssh/id_rsa
        borgmatic_ssh_manage_known_hosts: false
