---
- name: Converge
  hosts: clients
  tasks:
    - name: "Include borgmatic"
      include_role:
        name: "borgmatic"
      vars:
        borgmatic_run_backup: yes
        borgmatic_location_source_directories:
          - /etc
        borgmatic_location_repositories:
          - borg@borgmatic-server:molecule
        borgmatic_storage_encryption_passphrase: molecule-test
        borgmatic_retention_keep_daily: 3
        # setup is done manually in "prepare"
        borgmatic_ssh_manage_key: false
        borgmatic_ssh_key_path: /root/.ssh/id_rsa
        borgmatic_ssh_manage_known_hosts: false
