#code: language=ansible
- name: Systemd service and timer are installed
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "644"
  loop:
    - borgmatic.service
    - borgmatic.timer

- name: Systemd timer is enabled and running
  systemd:
    daemon_reload: yes
    name: borgmatic.timer
    enabled: yes
    state: started
