- name: Generate config variables # noqa var-spacing
  ansible.builtin.set_fact:
    # -> dict of config var name and actual value
    _borgmatic_configvars: "{{ _borgmatic_configvars | d({}) | combine({ item: lookup('vars', item )} ) }}"
  # -> List of all variable names that we need to lookup for our config
  loop: "{{ query('varnames', '^borgmatic_(' + borgmatic_config_sections | join('|') + ')_') }}"

- name: Config is installed
  template:
    src: config.yaml.j2
    dest: "{{ borgmatic_config_path }}/config.yaml"
    owner: root
    group: root
    mode: "640"

- name: Initialize repos
  command: "borgmatic --init --encryption {{ borgmatic_init_encryption }}"
  register: _borgmatic_init_command
  changed_when: _borgmatic_init_command.stdout | length > 0
  when: borgmatic_init_repos
