- name: Borg and borgmatic are installed
  apt:
    name:
      - borgmatic
      - borgbackup
    update_cache: yes

- name: Borgmatic config path is present
  file:
    path: "{{ borgmatic_config_path }}"
    state: directory
    mode: "750"
    owner: root
    group: root
