---
# defaults file for borgmatic
# Non-required borgmatic configuration variables are not set by default and do not appear here.
borgmatic_install: yes

borgmatic_config_path: /etc/borgmatic

borgmatic_setup_backup: yes
borgmatic_init_repos: yes
borgmatic_init_encryption: repokey

borgmatic_ssh_manage_key: yes
borgmatic_ssh_key_path: "{{ borgmatic_config_path }}/id_rsa"
borgmatic_ssh_manage_known_hosts: yes
borgmatic_ssh_known_hosts_file: "{{ borgmatic_config_path }}/known_hosts"

borgmatic_manage_config: yes
#borgmatic_location_source_directories:
#borgmatic_location_repositories Required

borgmatic_manage_schedule: yes
borgmatic_schedule_on: daily
borgmatic_schedule_max_random_delay: 1800
borgmatic_schedule_harden: no
borgmatic_schedule_require_ac_power: no
borgmatic_schedule_persistent: no
borgmatic_schedule_wakeup: no

borgmatic_schedule_check_job: no
borgmatic_schedule_check_job_time: "Mon 12:00"
borgmatic_schedule_check_job_checks:
  - repository
  - archives

borgmatic_run_backup: no
